"""Generates a simple, self-contained HTML report for the admin demo."""
from __future__ import annotations

import html
from typing import List

from .models import ScreeningResult

_BANNER = (
    "DEMONSTRATION PROTOTYPE — synthetic data only, no PHI. "
    "Criteria shown are illustrative and are NOT MCG content. "
    "All notifications are dry-run. Decision support only; a physician "
    "makes every admission decision."
)


def render_html(results: List[ScreeningResult]) -> str:
    total = len(results)
    met = [r for r in results if r.meets_criteria]

    rows = []
    for r in results:
        p = r.patient
        if r.meets_criteria:
            badges = " ".join(
                f'<span class="badge">{html.escape(m.label)} '
                f"&rarr; {html.escape(m.recommended_status)}</span>"
                for m in r.matches
            )
            status = f'<td class="met">{badges}</td>'
            cls = "row-met"
        else:
            status = '<td class="nomet">No criteria met</td>'
            cls = ""
        rows.append(
            f"<tr class='{cls}'>"
            f"<td>{html.escape(p.bed)}</td>"
            f"<td>{html.escape(p.name)}<br><small>MRN {html.escape(p.mrn)} "
            f"&middot; {p.age}{html.escape(p.sex)}</small></td>"
            f"<td>{html.escape(p.chief_complaint)}</td>"
            f"{status}"
            f"</tr>"
        )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ED Admission-Criteria Screen — Prototype</title>
<style>
  body {{ font-family: system-ui, sans-serif; margin: 0; color: #1a2330;
         background: #f4f6fb; }}
  .wrap {{ max-width: 980px; margin: 0 auto; padding: 24px; }}
  .banner {{ background: #fff4d6; border: 1px solid #e0c068; color: #6b4e00;
             padding: 12px 16px; border-radius: 8px; font-size: 14px;
             margin-bottom: 20px; }}
  h1 {{ font-size: 22px; margin: 0 0 4px; }}
  .sub {{ color: #5a6678; margin-bottom: 20px; }}
  .stats {{ display: flex; gap: 16px; margin-bottom: 20px; }}
  .stat {{ background: #fff; border-radius: 10px; padding: 14px 18px;
           box-shadow: 0 1px 3px rgba(0,0,0,.08); flex: 1; }}
  .stat .n {{ font-size: 28px; font-weight: 700; }}
  .stat .l {{ color: #5a6678; font-size: 13px; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff;
           border-radius: 10px; overflow: hidden;
           box-shadow: 0 1px 3px rgba(0,0,0,.08); }}
  th, td {{ text-align: left; padding: 12px 14px; border-bottom: 1px solid #eef1f6;
            font-size: 14px; vertical-align: top; }}
  th {{ background: #2b3a55; color: #fff; font-size: 12px;
        text-transform: uppercase; letter-spacing: .04em; }}
  .row-met {{ background: #eafaf0; }}
  .met {{ color: #15803d; }}
  .nomet {{ color: #8a93a3; }}
  small {{ color: #8a93a3; }}
  .badge {{ display: inline-block; background: #15803d; color: #fff;
            border-radius: 999px; padding: 2px 10px; font-size: 12px;
            margin: 2px 2px 0 0; }}
  footer {{ color: #8a93a3; font-size: 12px; margin-top: 18px; }}
</style>
</head>
<body>
  <div class="wrap">
    <div class="banner">{html.escape(_BANNER)}</div>
    <h1>ED Admission-Criteria Screen</h1>
    <div class="sub">Automated utilization-review pass over the ED trackboard</div>
    <div class="stats">
      <div class="stat"><div class="n">{total}</div>
        <div class="l">Patients on board</div></div>
      <div class="stat"><div class="n">{len(met)}</div>
        <div class="l">Met admission criteria</div></div>
      <div class="stat"><div class="n">{total - len(met)}</div>
        <div class="l">No criteria met</div></div>
    </div>
    <table>
      <thead><tr><th>Bed</th><th>Patient</th><th>Chief complaint</th>
        <th>Screen result</th></tr></thead>
      <tbody>
        {"".join(rows)}
      </tbody>
    </table>
    <footer>Generated by the ER MCG-screening prototype. Production replaces
    the demo criteria with the licensed MCG Cite / Indicia API and the dry-run
    notifier with an IT-sanctioned TigerConnect integration under a BAA.</footer>
  </div>
</body>
</html>
"""
